create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) on delete cascade not null unique, -- unique предотвращает дубли
  first_name text,
  last_name text,
  middle_name text,
  avatar text,
  city text,
  city_code text,
  description text,
  types jsonb not null default '[]'::jsonb,
  styles jsonb not null default '[]'::jsonb,
  segments jsonb not null default '[]'::jsonb,
  experience text,
  status text,
  created_at timestamptz not null default (now() AT TIME ZONE 'Europe/Moscow')
);

create index if not exists profiles_owner_id_idx on public.profiles(owner_id);

alter table public.profiles enable row level security;

-- Политики RLS
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = owner_id);

create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = owner_id);

create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = owner_id);

create policy "profiles_delete_own" on public.profiles
  for delete using (auth.uid() = owner_id);
